included:
  - Baemin

excluded:
  - Pods
  - Carthage
  - DerivedData
  - Build
  - Baemin/Generated
  - Baemin/Resources/Generated

# 자주 쓰는 opt-in 규칙
opt_in_rules:
  - sorted_imports
  - empty_count
  - explicit_init
  - discouraged_optional_boolean
  - discouraged_object_literal
  - yoda_condition

# Analyzer 룰은 여기!
analyzer_rules:
  - unused_import

# 전역으로 끄는 규칙
disabled_rules:
  - large_tuple
  - redundant_string_enum_value
  - function_parameter_count
  - trailing_whitespace

# 길이/복잡도 한도
line_length:
  warning: 120
  error: 160
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  allowed_symbols: "_"
  min_length:
    warning: 2
  excluded: [id, URL, url, x, y, i, j]

type_name:
  min_length: 3
  max_length: { warning: 40, error: 50 }
  excluded: [ID, URL, T, R]

file_length: { warning: 400, error: 800 }
type_body_length: { warning: 300, error: 600 }
function_body_length: { warning: 80, error: 200 }

# nesting의 올바른 키만 사용
nesting:
  type_level: 2
  function_level: 2

cyclomatic_complexity: { warning: 12, error: 20 }

# 불필요 공백/개행(과하지 않게)
vertical_whitespace:
  max_empty_lines: 1

reporter: "xcode"

